# Generated by Django 5.1.4 on 2025-02-17 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('profiles', '0002_profilemodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='author.authormodel'),
        ),
    ]
